apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
  endpoints:
  - port: http
    path: /prometheus
    interval: 30s
  namespaceSelector:
    matchNames:
    - jenkins